name: taiwan_zip
description: Map zip code to cities in Taiwan
version: 0.3.0
repository: https://github.com/yh-luo/taiwan_zip

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.19.2