name: taiwan_zip
description: A helper package to get three-digits zip codes by districts in Taiwan.
version: 0.4.0
repository: https://github.com/yh-luo/taiwan_zip

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.19.2